CXX=g++
AR=ar
INCDIR=include
SRCDIR=src
OBJDIR=obj
LIBDIR=lib
CXXFLAGS= -g -c -Wall -I$(INCDIR) 
ARFLAGS=rcs
SOURCE_FILES=commfrac.cpp
SOURCES=$(patsubst %.cpp,$(SRCDIR)/%.cpp,$(SOURCE_FILES))
OBJECT_FILES=$(patsubst %.cpp,%.o,$(SOURCE_FILES))
OBJECTS=$(patsubst %.o,$(OBJDIR)/%.o,$(OBJECT_FILES))

LIBNAME=libcommfrac.a
LIB=$(LIBDIR)/$(LIBNAME)

all: $(SOURCES) $(LIB)
    
$(LIB): $(OBJDIR) $(OBJECTS) $(LIBDIR) $(SOURCES)
	$(AR) $(ARFLAGS) -o $@ $(OBJECTS)

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp
	$(CXX) $(CXXFLAGS) $< -o $@

$(OBJDIR):
	mkdir -p $(OBJDIR)

$(LIBDIR):
	mkdir -p $(LIBDIR)

clean:
	rm -f $(OBJECTS)
